# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-21 13:50
from __future__ import unicode_literals

import customfilefield.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadfile',
            options={'ordering': ['username']},
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='username',
            field=models.CharField(default='nobody', max_length=50, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='datafile',
            field=models.FileField(storage=customfilefield.storage.FileStorage(), upload_to='datasets', verbose_name='datafile'),
        ),
    ]
