# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 02:57
from __future__ import unicode_literals

import customfilefield.storage
from django.db import migrations, models
import upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20170521_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='datafile',
            field=models.FileField(storage=customfilefield.storage.FileStorage(), upload_to=upload.models.get_file_path, verbose_name='datafile'),
        ),
    ]
